---
- name: Install problematic desktop environment
  hosts: all

  vars:
    cask_packages:
      - dropbox
      - itau
      - libreoffice

  tasks:
    - name: Install Homebrew Cask packages
      homebrew_cask: name={{ item }} state=present
      with_items: "{{ cask_packages }}"

