---
- name: Install desktop environment
  hosts: all

  vars:
    packages:
      - macvim

    cask_packages:
      - dropbox
      - electrum
      - firefox
      - google-chrome
      - itau
      - iterm2
      - libreoffice
      - screenhero
      - shiftit
      - skype
      - telegram
      - visual-studio-code

  tasks:
    - name: Install Homebrew packages
      homebrew: name={{ item }} state=latest
      with_items: "{{ packages }}"

    - name: Install Homebrew Cask packages
      homebrew_cask: name={{ item }} state=present
      with_items: "{{ cask_packages }}"

