---
- name: Install terminal environment
  hosts: all

  vars:
    packages:
      - ag
      - ffmpeg
      - ghc
      - gifsicle
      - git
      - heroku
      - imagemagick
      - passpie
      - yarn
      - wget
      - pyenv
      - pyenv-virtualenv
      - pyenv-virtualenvwrapper

    rubygems:
      - travis

    # todo:
    #   - rvm
    #   - nvm
    #   - yadr

    # db:
    #   - mysql
    #   - postgresql
    #   - redis
    #   - mongodb

  tasks:
    - name: Install Homebrew packages
      homebrew: name={{ item }} state=latest
      with_items: "{{ packages }}"

    - name: Install ruby gems
      gem: name={{ item }} state=present
      with_items: "{{ rubygems }}"
