---
- name: Install terminal environment
  hosts: all

  vars:
    taps:
      - homebrew/versions

    packages:
      - ag
      - ghc
      - git

    rubygems:
      - travis

  tasks:
    - name: Add Homebrew taps
      homebrew_tap: name={{ item }} state=present
      with_items: "{{ taps }}"

    - name: Install Homebrew packages
      homebrew: name={{ item }} state=latest
      with_items: "{{ packages }}"

    - name: Install ruby gems
      gem: name={{ item }} state=present
      with_items: "{{ rubygems }}"

