---
- name: Install terminal environment
  hosts: all

  vars:
    unwanted_packages:
      - htop-osx

    packages:
      - ag
      - docker-machine
      - ffmpeg
      - ghc
      - gifsicle
      - git
      - heroku
      - htop
      - hub
      - imagemagick
      - passpie
      - pyenv
      - pyenv-virtualenv
      - pyenv-virtualenvwrapper
      - shellcheck
      - wget
      - yarn

    rubygems:
      - travis

    # todo:
    #   - rvm
    #   - nvm
    #   - yadr

    # db:
    #   - mysql
    #   - postgresql
    #   - redis
    #   - mongodb

  tasks:
    - name: Uninstall Homebrew packages
      homebrew: name={{ item }} state=absent
      with_items: "{{ unwanted_packages }}"

    - name: Install Homebrew packages
      homebrew: name={{ item }} state=latest
      with_items: "{{ packages }}"

    - name: Install ruby gems
      gem: name={{ item }} state=present
      with_items: "{{ rubygems }}"