---
- name: Install terminal environment
  hosts: all

  vars:
    packages:
      - ag
      - ghc
      - git
      - passpie

    rubygems:
      - travis

  tasks:
    - name: Install Homebrew packages
      homebrew: name={{ item }} state=latest
      with_items: "{{ packages }}"

    - name: Install ruby gems
      gem: name={{ item }} state=present
      with_items: "{{ rubygems }}"
